baseURL = 'http://wiiutitledatabase.github.io/'
languageCode = 'en-us'
title = 'Wii U Title Database'
theme = "hugo-geekdoc"

#Required to get well formatted code blocks
pygmentsUseClasses = true
pygmentsCodeFences = true
disablePathToLower = true
enableGitInfo = true

geekdocLogo = "/images/logo.png"

geekdocRepo = "https://github.com/wiiutitledatabase/website/"